# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcc3847b9f29c205e3039910fdb488fb6d0d2234da842bb7d209eb8ea4951e8f51c2c9eb609c2fb2c554a8b15aaba8634184304f5328f06ec24aee3b5008d2d9
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

test:
  secret_key_base: c009cc2d75ae4040afd359fd2f85c3d64e5ab7ef36e5c40c8f553c7e9473862b6146ec687e1b6bec21f520e7d9289c35ef897877e6b45f5245c91e8de9ac09ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
